#!/usr/bin/env python

import sys
from http.server import HTTPServer, SimpleHTTPRequestHandler
from ssl import PROTOCOL_TLS_SERVER, SSLContext


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} CERTFILE KEYFILE")
        sys.exit(1)

    tls = SSLContext(PROTOCOL_TLS_SERVER)
    tls.load_cert_chain(certfile=sys.argv[1], keyfile=sys.argv[2])

    httpd = HTTPServer(("0.0.0.0", 8000), SimpleHTTPRequestHandler)
    httpd.socket = tls.wrap_socket(httpd.socket, server_side=True)
    httpd.serve_forever()
